version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 3
  - package-ecosystem: npm
    directory: "/apps/frontend"
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
  - package-ecosystem: gradle
    directory: "/apps/backend"
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
