apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: fagprove-monorepo-frontend-staging
  namespace: laerlinger
  labels:
    team: laerlinger
spec:
  image: {{image}}
  port: 4321
  ingresses:
    - https://fagprove-monorepo-frontend-staging.ekstern.dev.nav.no
  liveness:
    path: /api/health
    initialDelay: 30
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /api/health
    initialDelay: 30
    timeout: 5
    failureThreshold: 3
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi
  replicas:
    min: 1
    max: 1
  env:
    - name: TZ
      value: Europe/Oslo
    - name: DECORATOR_ENV
      value: dev
    - name: BACKEND_URL
      value: http://fagprove-monorepo-backend-staging
  accessPolicy:
    outbound:
      rules:
        - application: fagprove-monorepo-backend-staging
      external:
        - host: dekoratoren.ekstern.dev.nav.no
