/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Root endpoint */
    get: operations['getRoot'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/hello': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** JSON greeting used by the frontend BFF demo */
    get: operations['getHello'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/internal/isalive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Internal liveness probe */
    get: operations['getInternalIsAlive'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/internal/isready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Internal readiness probe */
    get: operations['getInternalIsReady'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/internal/metrics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Prometheus metrics */
    get: operations['getInternalMetrics'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/cities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all cities */
    get: operations['listCities'];
    put?: never;
    /** Create a new city */
    post: operations['createCity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/cities/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ResourceId'];
      };
      cookie?: never;
    };
    /** Get a city by ID */
    get: operations['getCity'];
    /** Update a city by ID */
    put: operations['updateCity'];
    post?: never;
    /** Delete a city by ID */
    delete: operations['deleteCity'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all users */
    get: operations['listUsers'];
    put?: never;
    /** Create a new user */
    post: operations['createUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ResourceId'];
      };
      cookie?: never;
    };
    /** Get a user by ID */
    get: operations['getUser'];
    /** Update a user by ID */
    put: operations['updateUser'];
    post?: never;
    /** Delete a user by ID */
    delete: operations['deleteUser'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    City: {
      /** @example Oslo */
      name: string;
      /** @example 709037 */
      population: number;
    };
    CityResponse: {
      id: number;
      name: string;
      population: number;
    };
    User: {
      /** @example Ola Nordmann */
      name: string;
      /** @example 30 */
      age: number;
    };
    UserResponse: {
      id: number;
      name: string;
      age: number;
    };
    Error: {
      type?: string;
      title: string;
      status: number;
      detail?: string;
    };
  };
  responses: {
    /** @description Invalid request body or parameters */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Resource not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
    /** @description Internal server error */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: {
    ResourceId: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getRoot: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Hello World greeting */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
    };
  };
  getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Greeting */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  getInternalIsAlive: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Application process is alive */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getInternalIsReady: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Application is ready to receive traffic */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getInternalMetrics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Prometheus exposition format */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
    };
  };
  listCities: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of all cities */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CityResponse'][];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  createCity: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['City'];
      };
    };
    responses: {
      /** @description City created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': number;
        };
      };
      400: components['responses']['BadRequest'];
      500: components['responses']['InternalError'];
    };
  };
  getCity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ResourceId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description City found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CityResponse'];
        };
      };
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  updateCity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ResourceId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['City'];
      };
    };
    responses: {
      /** @description City updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  deleteCity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ResourceId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description City deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  listUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of all users */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'][];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  createUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['User'];
      };
    };
    responses: {
      /** @description User created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': number;
        };
      };
      400: components['responses']['BadRequest'];
      500: components['responses']['InternalError'];
    };
  };
  getUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ResourceId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  updateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ResourceId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['User'];
      };
    };
    responses: {
      /** @description User updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  deleteUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ResourceId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
}
