name: Copilot Customization Sync
on:
  schedule:
    - cron: '0 7 * * *' # Daglig kl. 07:00 UTC
  workflow_dispatch:
jobs:
  sync:
    uses: navikt/copilot/.github/workflows/copilot-customization-sync.yml@28d1537db0286b35127dc760cf7a80031dd38925 # main 2026-05-30
    permissions:
      contents: write
      pull-requests: write
