name: Copilot Customization Sync
on:
  schedule:
    - cron: '0 7 * * *' # Daglig kl. 07:00 UTC
  workflow_dispatch:
jobs:
  sync:
    uses: navikt/copilot/.github/workflows/copilot-customization-sync.yml@7f41e92864c32099217b717672dadaab33f8890c # main 2026-05-30
    permissions:
      contents: write
      pull-requests: write
